### ISSUE TITLE
Benchmarks?

### ISSUE THREAD

**Issue by nexus1203** [Smirkey/powerboxes#30]
How the benchmark images are obtained?
My tests shows that cv2.dnn.NMSBoxes is much faster in comparison with the powerboxes (nms and rtree_nms).

```
import numpy as np


def nms_fast(boxes, scores, iou_thr, score_thr=0.0):
    """
    Perform fast Non-Maximum Suppression (NMS) on a list of bounding boxes.
    
    Args:
    boxes (np.ndarray): An array of bounding boxes in the format [x1, y1, x2, y2].
    scores (np.ndarray): Array of scores for each box.
    iou_thr (float): The IOU threshold to determine if boxes should be suppressed.
    score_thr (float): Score threshold for suppressing low-scoring boxes.

    Returns:
    List[int]: Indices of boxes that are kept.
    """

    # Filter out boxes with scores below the threshold
    valid_boxes = np.where(scores >= score_thr)[0]
    boxes = boxes[valid_boxes]
    scores = scores[valid_boxes]

    if len(boxes) == 0:
        return []

    if boxes.dtype.kind == "i":
        boxes = boxes.astype("float")

    # Initialize the list of picked indexes
    pick = []

    # Grab the coordinates of the bounding boxes
    x1, y1, x2, y2 = boxes[:, 0], boxes[:, 1], boxes[:, 2], boxes[:, 3]

    # Compute the area of the bounding boxes
    area = (x2 - x1) * (y2 - y1)

    # Sort the boxes by their scores in descending order
    idxs = np.argsort(scores)[::-1]

    while len(idxs) > 0:
        i = idxs[0]
        pick.append(i)

        xx1 = np.maximum(x1[i], x1[idxs[1:]])
        yy1 = np.maximum(y1[i], y1[idxs[1:]])
        xx2 = np.minimum(x2[i], x2[idxs[1:]])
        yy2 = np.minimum(y2[i], y2[idxs[1:]])

        w = np.maximum(0, xx2 - xx1)
        h = np.maximum(0, yy2 - yy1)

        # Calculate the IOU
        inter_area = w * h
        eps = 1e-16  # to avoid division by zero
        union_area = area[i] + area[idxs[1:]] - inter_area + eps
        iou = inter_area / union_area

        # Keep only boxes with an IOU less than the threshold
        idxs = idxs[np.where(iou < iou_thr)[0] + 1]

    return pick


def benchmark_nms_methods(box_counts):
    from time import perf_counter
    import powerboxes as pb
    import cv2

    pb_nms_times = []
    pb_rtree_nms_times = []
    numpy_nms_times = []
    opencv_nms_times = []

    image_size = 10_000
    iou_thr = 0.5

    for n_predictions in box_counts:
        topleft = np.random.randint(0, image_size, size=(n_predictions, 2))
        width_height = np.random.randint(0,
                                         image_size,
                                         size=(n_predictions, 2))
        boxes = np.concatenate([topleft, topleft + width_height], axis=1)
        scores = np.random.uniform(0, 1, size=(n_predictions, ))

        # PowerBoxes NMS
        start = perf_counter()
        for _ in range(10):
            keep = pb.nms(boxes, scores, iou_thr, score_threshold=0.0)
        end = perf_counter()
        pb_nms_times.append((end - start) / 10)

        # PowerBoxes RTree NMS
        start = perf_counter()
        for _ in range(10):
            keep = pb.rtree_nms(boxes, scores, iou_thr, score_threshold=0.0)
        end = perf_counter()
        pb_rtree_nms_times.append((end - start) / 10)

        # Numpy NMS
        start = perf_counter()
        for _ in range(10):
            keep = nms_fast(boxes, scores, iou_thr)
        end = perf_counter()
        numpy_nms_times.append((end - start) / 10)

        # OpenCV NMS
        start = perf_counter()
        for _ in range(10):
            keep = cv2.dnn.NMSBoxes(boxes.tolist(), scores.tolist(), 0.0,
                                    iou_thr)
        end = perf_counter()
        opencv_nms_times.append((end - start) / 10)

    return pb_nms_times, pb_rtree_nms_times, numpy_nms_times, opencv_nms_times


if __name__ == '__main__':
    from matplotlib import pyplot as plt

    box_counts = [10, 100, 1_000, 10_000, 30_000, 50_000]
    pb_nms_times, pb_rtree_nms_times, numpy_nms_times, opencv_nms_times = benchmark_nms_methods(
        box_counts)

    # Width of the bars
    bar_width = 0.2

    # Setting the position of the bars
    r1 = np.arange(len(pb_nms_times))
    r2 = [x + bar_width for x in r1]
    r3 = [x + bar_width for x in r2]
    r4 = [x + bar_width for x in r3]

    # Creating the bar chart
    plt.figure(figsize=(14, 8))
    plt.bar(r1,
            pb_nms_times,
            color='blue',
            width=bar_width,
            edgecolor='grey',
            label='PowerBoxes NMS')
    plt.bar(r2,
            pb_rtree_nms_times,
            color='red',
            width=bar_width,
            edgecolor='grey',
            label='PowerBoxes RTree NMS')
    plt.bar(r3,
            numpy_nms_times,
            color='green',
            width=bar_width,
            edgecolor='grey',
            label='Numpy NMS')
    plt.bar(r4,
            opencv_nms_times,
            color='orange',
            width=bar_width,
            edgecolor='grey',
            label='OpenCV NMS')

    # Adding labels
    plt.xlabel('Number of Boxes', fontweight='bold')
    plt.ylabel('Average Time per Run (seconds)', fontweight='bold')
    plt.xticks([r + bar_width for r in range(len(pb_nms_times))], box_counts)
    plt.yscale('log')
    # Creating a legend and showing the plot
    plt.title('NMS Methods Performance Comparison')
    plt.legend()
    plt.savefig('nms_benchmark.png')
    plt.show()
```

![nms_benchmark](https://github.com/Smirkey/powerboxes/assets/70212520/36c9bd66-806c-4fba-85e1-295beabd3d4f)

# Update:

For 100 runs on 11th gen Intel Core i7 (2.8GHz) with 4 cores and 8 Logical Processors the results are shown below. For smaller number of boxes, powerboxes is indeed faster than the alternatives.

![nms_benchmark](https://github.com/Smirkey/powerboxes/assets/70212520/bbec7fd1-689a-48f2-b2c3-3c6055ba794d)

**Comment by Smirkey** [comment]
Hi :)
Thanks for looking into this ! After some investigation I found why the results you obtained are different than the ones showed in the readme.
Two things:

First, the number of trials seems too low for small number of boxes (<1000), we should plot error bars ... after increasing number of trials to 100 I end up with the following results (on a `12th Gen Intel(R) Core(TM) i7-1250U` cpu with 12 cpus
![plot](https://github.com/Smirkey/powerboxes/assets/25055427/398ce688-0dce-45c6-a58b-0f14d2d0634d)


The benchmarks were ran on **google colab which only has two cpu cores**. Since numpy and opencv rely on multi threading, the higher the number of cores, the better the performance. Powerboxes doesn't implement any multithreading for NMS yet. This could be a good way to process faster high number of boxes

**Comment by Smirkey** [comment]
Hi ! 
Thanks for taking the time to look this :) and for the numpy nms function 
The discrepancy between the benchmarks in the readme indeed came from the number of trials which was too low in your case (number of cpu cores doesn't matter since neither numpy nor opencv seem to use multithreading here)

I updated your [code](https://gist.github.com/Smirkey/5b8ed6ba84a6df1b85ec1aae9a427510) (thanks again) to plot error bars, and to increase number of trials. I will integrate this in the colab notebook which holds the benchmarks visualizations. Here are the results I obtain on my laptop with a `12th Gen Intel(R) Core(TM) i7-1250U` cpu
![plot](https://github.com/Smirkey/powerboxes/assets/25055427/c6ad9750-758f-46a2-9a6a-f3177f82fea3)

One thing to note is that powerboxes nms scales particularly badly with the number of boxes compared to opencv, which in turn performs badly on a small number of boxes. The logic in [opencv](https://github.com/opencv/opencv/blob/a8ec6586118c3f8e8f48549a85f2da7a5b78bcc9/modules/dnn/src/nms.inl.hpp#L57-L102) is quite different than what I implemented. I will look into it and  see if there's a way to take best of both approaches.

**Comment by nexus1203** [comment]
You are right about the threading. Numpy version is basically using vectorization to speedup the calculations. In fact, I tried Cython version of the same thing and yet numpy's native python implementation is twice as faster. Using jit (e.g. Jax or Numba) doesn't help either as the code cannot be parallelized efficiently. 

As for OpenCV, it does uses adaptive NMS, however, implementation is unclear as I haven't seen the C++ code yet. Another thing is that OpenCV version of the code be further optimized using OPENCL or CUDA acceleration which is such a pain to setup in python. 

What you have here (powerboxes) is a very well implemented and very efficient. Especially without threading, the performance is quite amazing.
